# Generated by Django 5.2.5 on 2025-09-04 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_reset_order_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='salesreport',
            old_name='total_sales',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='salesreport',
            name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='Guest', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Preparing', 'Preparing'), ('Ready', 'Ready'), ('Served', 'Served')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='salesreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
